language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - env: TOXENV=coverage
install:
- pip install -U pip tox codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: cfhamlet
  password:
    secure: CepQGAyZE2tA7mwpAJ/I1dpxnZYGXN/fCCQZAh7ngVskYnGbnrvPu7EiZ8CcX1BL04vU6LzAesE3oNqGI9S2TXxChCocVM1tIG46pbkXdMGGQSscp2zVMTQAqZUXiRUDFDvTEjPRLD4JB/i0yJxQa5rlCzGAHPfXat3HLGS+SnAM64Ip9cO2dVdE4Q+u+Ungwnzv7ebnvSURrrmCT7ey57k02UKJsP1rRBFiec55R30ILVsvNOqWNmhwwgwVm7X3c5iUh9B55uDaFn0hEVyEsY6xGqCBlviVIymxQe/+32BMPc2JjKqrTTIUwd/+XrRbdAlp2jD8/SUY3wjz+PcZRaPjZ8AQ4w2EnofYghB/8eZ/8weM2dg2BAbTHpnrJkHG30Q62dSy2qFtlOjiv0SeJbV8W5Mfc3eW2AoaHBMjKl/RXEYF0nE6zqE+G9kVfEn8oD+fE3mUJ+4pAAN0IWhrJH8B9koUiIpTKfwrfGM7yp+peY0ygblKsZmkuGoniZa1f/3cBulhBk0HRJlSByvRj1LFyW+C9S1MGKk72k4mzG6JVVp3ioFyU7fwoyTNw+JBMZT9x7Kj5kFbMPZMBzhmN5Zq89NbKcEu3d01NSzhBfFC/rm/DPvZEsaFFicTqBwICcRUQPKHaHXTPkA9uRA7fyJ6mdyZLHIluwEgXGWIbQA=
  on:
    tags: true
    condition: ${TOXENV} == py27
